---
- name: Ensure the APT cache is up-to-date
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Perform a full system upgrade
  apt:
    upgrade: "safe"

- name: Install basic common packages
  apt:
    name: "{{ item }}"
  with_items: "{{ common_packages }}"

# vim: set ft=yaml sw=2:
